apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: aliens-deployment 
spec: 
  selector: 
    matchLabels: 
      app: aliens 
  replicas: 2 
  template: 
    metadata: 
      labels: 
        app: aliens
    spec: 
      containers: 
      - name: aliens 
        image: elijahkyule/aliens
        ports: 
        - containerPort: 80 
--- 
kind: Service 
apiVersion: v1 
metadata: 
  name: aliens-service 
spec: 
  selector: 
    app: aliens
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 32100 
  type: NodePort 